"""
Embedding Service: handles text chunking, embedding generation, and ChromaDB storage.

This is the "ingestion" side of RAG — it takes raw resume/JD text,
splits it into meaningful chunks, generates vector embeddings for each chunk,
and stores them in ChromaDB for later retrieval.

Key concepts:
  - Chunking: splitting long text into smaller pieces so each piece fits in
    the LLM's context and represents one coherent idea.
  - Embeddings: converting text into dense numerical vectors (arrays of floats)
    that capture semantic meaning. Similar texts get similar vectors.
  - ChromaDB: a vector database that stores these embeddings and lets you
    search for the most similar ones given a query.
"""
import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
from langchain_text_splitters import RecursiveCharacterTextSplitter

from app.config import settings


class EmbeddingService:
    """
    Manages the ChromaDB vector store and embedding operations.

    Each resume gets its own ChromaDB collection (namespaced by resume_id)
    so searches are scoped to one resume at a time.
    """

    def __init__(self):
        # PersistentClient stores data on disk so it survives restarts.
        # The path is configured in settings (default: ./chroma_data)
        self.client = chromadb.PersistentClient(path=settings.chroma_persist_dir)

        # SentenceTransformerEmbeddingFunction wraps the sentence-transformers library.
        # "all-MiniLM-L6-v2" produces 384-dimensional vectors.
        # It's small (~80MB), fast, and good enough for semantic search.
        self.embedding_fn = SentenceTransformerEmbeddingFunction(
            model_name=settings.embedding_model
        )

        # Text splitter from LangChain — splits text into chunks.
        # RecursiveCharacterTextSplitter tries to split on natural boundaries
        # (paragraphs → sentences → words) rather than cutting mid-sentence.
        #   - chunk_size=500: target ~500 characters per chunk
        #   - chunk_overlap=50: each chunk overlaps with the next by 50 chars
        #     so context isn't lost at chunk boundaries
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=500,
            chunk_overlap=50,
            separators=["\n\n", "\n", ". ", " ", ""],
        )

    def _get_collection_name(self, resume_id: str) -> str:
        """Generate a ChromaDB collection name for a resume."""
        # ChromaDB collection names must be 3-63 chars, alphanumeric + underscores
        return f"resume_{str(resume_id).replace('-', '_')}"

    def chunk_text(self, text: str) -> list[str]:
        """
        Split text into semantically meaningful chunks.

        Returns a list of text chunks, each ~500 characters with 50-char overlap.
        """
        chunks = self.text_splitter.split_text(text)
        return [chunk.strip() for chunk in chunks if chunk.strip()]

    def store_chunks(self, resume_id: str, chunks: list[str]) -> None:
        """
        Store text chunks in ChromaDB with their embeddings.

        Each chunk gets:
          - A unique ID (chunk_0, chunk_1, ...)
          - The text content (stored as a "document" in ChromaDB)
          - An embedding vector (auto-generated by the embedding function)
          - Metadata (chunk index, for reference)

        ChromaDB automatically generates embeddings using our
        SentenceTransformerEmbeddingFunction when we add documents.
        """
        collection_name = self._get_collection_name(resume_id)

        # Delete existing collection if re-uploading
        try:
            self.client.delete_collection(collection_name)
        except ValueError:
            pass  # Collection doesn't exist yet, that's fine

        collection = self.client.get_or_create_collection(
            name=collection_name,
            embedding_function=self.embedding_fn,
        )

        # Add all chunks in one batch
        collection.add(
            documents=chunks,
            ids=[f"chunk_{i}" for i in range(len(chunks))],
            metadatas=[{"chunk_index": i} for i in range(len(chunks))],
        )

    def vector_search(self, resume_id: str, query: str, n_results: int = 10) -> list[dict]:
        """
        Search ChromaDB for chunks most similar to the query.

        This is pure vector/semantic search — it finds chunks whose
        embeddings are closest to the query embedding (cosine similarity).

        Returns a list of dicts with 'text', 'score', and 'chunk_index'.
        """
        collection_name = self._get_collection_name(resume_id)

        try:
            collection = self.client.get_collection(
                name=collection_name,
                embedding_function=self.embedding_fn,
            )
        except ValueError:
            return []  # Collection doesn't exist

        results = collection.query(
            query_texts=[query],
            n_results=min(n_results, collection.count()),
        )

        # ChromaDB returns nested lists (one per query). We only send one query.
        documents = results["documents"][0] if results["documents"] else []
        distances = results["distances"][0] if results["distances"] else []
        metadatas = results["metadatas"][0] if results["metadatas"] else []

        return [
            {
                "text": doc,
                "score": 1 - dist,  # ChromaDB returns distances; convert to similarity
                "chunk_index": meta.get("chunk_index", i),
            }
            for i, (doc, dist, meta) in enumerate(zip(documents, distances, metadatas))
        ]

    def get_all_chunks(self, resume_id: str) -> list[str]:
        """
        Retrieve all stored chunks for a resume.
        Used by BM25 search (which needs the full chunk list to build its index).
        """
        collection_name = self._get_collection_name(resume_id)

        try:
            collection = self.client.get_collection(
                name=collection_name,
                embedding_function=self.embedding_fn,
            )
        except ValueError:
            return []

        results = collection.get()
        return results["documents"] if results["documents"] else []


# Singleton instance
embedding_service = EmbeddingService()
